# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0ad124c3beb941a3463dba4a5965f6f8"
name = "v4-a"
handle = "v4-a"
application_url = "https://reuters-subtle-onto-lab.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "anuragdev-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://reuters-subtle-onto-lab.trycloudflare.com/auth/callback",
  "https://reuters-subtle-onto-lab.trycloudflare.com/auth/shopify/callback",
  "https://reuters-subtle-onto-lab.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
