# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d85152038999779e3ca010b8f6992d1"
name = "v1-a"
handle = "v1-a-2"
application_url = "https://surprised-savannah-hydraulic-edwards.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "poc-v2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://surprised-savannah-hydraulic-edwards.trycloudflare.com/auth/callback",
  "https://surprised-savannah-hydraulic-edwards.trycloudflare.com/auth/shopify/callback",
  "https://surprised-savannah-hydraulic-edwards.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
