# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9ad2da8a749426016d0cfe7621eccfd4"
name = "qr-code-poc2"
application_url = "https://bidding-vendor-mauritius-dating.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "poc-v2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://bidding-vendor-mauritius-dating.trycloudflare.com/auth/callback",
  "https://bidding-vendor-mauritius-dating.trycloudflare.com/auth/shopify/callback",
  "https://bidding-vendor-mauritius-dating.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
