# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4ec651f5a75504841f4675e92d8366e4"
name = "extensive-enterprise-app"
handle = "extensive-enterprise-app-9"
application_url = "https://convention-kurt-anne-creative.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "poc-v2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://convention-kurt-anne-creative.trycloudflare.com/auth/callback",
  "https://convention-kurt-anne-creative.trycloudflare.com/auth/shopify/callback",
  "https://convention-kurt-anne-creative.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
